### ISSUE TITLE
[BIN] Auto configuration fail on Lyon for json probe

### ISSUE THREAD

**Issue by clement-parisot** [lpouillo/kwapi-g5k#37]
Json probe configuration is buggy on Lyon site. Needs to fix probe_ids for this driver.

**Comment by lpouillo** [comment]
Hercule qui fout la merde?

**Comment by clement-parisot** [comment]
solution temporaire pour lyon dans le commit #e0ee16. Hercule n'apparaît pas.

**Comment by lpouillo** [comment]
Je ferme non ?
