### ISSUE TITLE
incoherence in KWAPI

### ISSUE THREAD

**Issue by lpouillo** [lpouillo/kwapi-g5k#38]
from cruiz

Hello,

I've just noted an incoherence in the KWAPI API. When executing the following request:

$curl -kn "https://api.grid5000.fr/3.0/sites/rennes//metrics/network_in/timeseries/?from=1450370360&to=1450370860&only=paranoia-3"
{
  "items": [
    {
      "from": 1450370360,
      "links": [
        {
          "href": "/sid/sites/rennes/metrics/network_in/timeseries/paranoia-3",
          "rel": "self",
          "type": "application/vnd.fr.grid5000.api.Timeseries+json;level=1"
        },
        {
          "href": "/sid/sites/rennes/metrics/network_in",
          "rel": "parent",
          "type": "application/vnd.fr.grid5000.api.Metric+json;level=1"
        }
      ],
      "resolution": 1,
      "timestamps": [
        1450370362.236516,
        1450370364.270576,
        1450370365.856885,
        1450370368.721628,

I'm able to get the data without any problem. However, the REST links are incoherent. They point to the sid version even though I use the version 3.0 of the API to perform the request.

**Comment by clement-parisot** [comment]
Bougé sur G5K

https://intranet.grid5000.fr/bugzilla/show_bug.cgi?id=9462
